schema_version: 2
network: mainnet
build_parameters:
  mint_version: 0
  admin_verification_key_hash: 4da965a049dfd15ed1ee19fba6e2974a0b79fc416dd1796a1f97f5e1
  orders_spend_randomizer: ""
  royalty_spend_admin: 4da965a049dfd15ed1ee19fba6e2974a0b79fc416dd1796a1f97f5e1
settings:
  hal_settings:
    allowed_minter: 4da965a049dfd15ed1ee19fba6e2974a0b79fc416dd1796a1f97f5e1
    hal_nft_price: 180000000
    payment_address: addr1x9g6q0szf6z9vw9uwmtz2hwpgs9u0mnd6jem99alcaqnaj4nrlr3te9hrgh92fh6mfxhq248qs3l5qx65a5fs9kfsteqv4qdnh
    minting_start_time: 1758221880000
  ref_spend_settings:
    ref_spend_admin: 4da965a049dfd15ed1ee19fba6e2974a0b79fc416dd1796a1f97f5e1
  minting_data:
    mpt_root_hash: 37c5aefffdbf4f0ffd9721dcfab18ba83bff60bbcbd521a49b873b76c801ae5a
    whitelist_mpt_root_hash: a35f44cd78d287a67e1ba020d8cdf4ec6d1307cedbf226ece28de1354668cba4
assigned_handles:
  settings:
    hal-settings: hal@handle_settings
    halref-settings: hal_pz@handle_settings
    halmntmpt-settings: hal_root@handle_settings
  scripts:
    halmntprx: hal_mnt_prxy@handle_contract
    halmnt: hal_mnt@handle_contract
    halmntmpt: hal_mnt_data@handle_contract
    halord: hal_ord_spnd@handle_contract
    halrefprx: hal_rf_sd_px@handle_contract
    halref: hal_ref_spnd@handle_contract
    halroy: hal_roy_spnd@handle_contract
ignored_settings:
  - settings.minting_data.mpt_root_hash
  - settings.minting_data.whitelist_mpt_root_hash
contracts:
  - contract_slug: halmntprx
    script_type: halmntprx
    old_script_type: hal_mint_proxy
    deployment_handle_slug: halmntprx
    build:
      contract_name: halmntprx.mint
      kind: minting_policy
  - contract_slug: halmnt
    script_type: halmnt
    old_script_type: hal_mint
    deployment_handle_slug: halmnt
    build:
      contract_name: halmnt.withdraw
      kind: validator
  - contract_slug: halmntmpt
    script_type: halmntmpt
    old_script_type: hal_minting_data
    deployment_handle_slug: halmntmpt
    build:
      contract_name: halmntmpt.spend
      kind: validator
  - contract_slug: halord
    script_type: halord
    old_script_type: hal_orders_spend
    deployment_handle_slug: halord
    build:
      contract_name: halord.spend
      kind: validator
  - contract_slug: halrefprx
    script_type: halrefprx
    old_script_type: hal_ref_spend_proxy
    deployment_handle_slug: halrefprx
    build:
      contract_name: halrefprx.spend
      kind: validator
  - contract_slug: halref
    script_type: halref
    old_script_type: hal_ref_spend
    deployment_handle_slug: halref
    build:
      contract_name: halref.withdraw
      kind: validator
  - contract_slug: halroy
    script_type: halroy
    old_script_type: hal_royalty_spend
    deployment_handle_slug: halroy
    build:
      contract_name: halroy.spend
      kind: validator
